### ISSUE TITLE
Removing Docker Antipattern

### ISSUE THREAD

**Issue by benyanke** [wger-project/docker#13] opened 2021-11-08 16:26 UTC
Hello,

Thanks for providing your app as a docker image! However, it's a bit of an anti-pattern to require manual shell commands on startup.

It would be more typical to run on container startup, with perhaps a flag set in an env var to enable or disable.

Would you be open to a PR which implements this? Something like:

```
ON_STARTUP_SYNC_EXERCISES=true

**Comment by benyanke** [comment] 2021-11-08 16:29
Note that this could be implemented so as to be non-disruptive to the current workflow, such that it's disabled by default and the old methods still work.

**Comment by rolandgeider** [comment] 2021-11-08 17:02
Hi! you are of course right. The problem is rather that the image does too much, it's used for development and production so there are a couple of more or less ugly workarounds. The cleaner solution would be to split them up so that this one doesn't have any manual steps.

**Comment by benyanke** [comment] 2021-11-08 21:50
For what it's worth, I think there's actually a lot of advantages to keeping one singular image if you're willing to consider it. Would you accept a PR adding these optional steps behind Env var flags, disabled by default?

**Comment by rolandgeider** [comment] 2021-11-08 21:58
I know what you mean, in the end the setup is very similar. Some clean up one of these days won't hurt 😄

As for the PR, sure! We should probably add flags to control synchronizing the exercises, downloading the images and the fixtures.

**Comment by benyanke** [comment] 2021-11-08 23:34
Cool! I'll try and send you one if I have a chance to work on it, or at least this issue is evidence of interest if someone else finds it and wishes to.

**Comment by rolandgeider** [comment] 2022-04-23 11:47
It is now possible to auto-sync this on startup (besides the ingredient info, which is only updated every couple of months or so), closing

**Closed by rolandgeider** 2022-04-23 11:47 UTC
