### ISSUE TITLE
Think about automating the upgrade process

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/docker#15] opened 2021-11-09 14:55 UTC
At the moment some changes from upstream require manual steps like database migrations. On one hand it would be nice if this would happen during startup, on the other hand... they are db migrations that could potentially make the user lose all their data.

**Comment by benyanke** [comment] 2021-11-12 05:43
This seems related to (but not exactly a duplicate of) my issue in #13.

When I get a chance to implement #13, I can add a run-migrations option too.

**Comment by rolandgeider** [comment] 2021-11-12 07:43
They are definitely related. I'm just not sure whether auto migrating is a good idea

**Comment by benyanke** [comment] 2021-11-12 12:56
In theory, migrations shouldn't lose user data, right? And are needed for the current codebase to run successfully, so must be run? I'm new to this app's stack still but that's how every other app I've used has worked.

**Comment by rolandgeider** [comment] 2021-11-12 15:35
Yes, and in all the project's history I don't think we had really complex migrations. I'm probably being too paranoid

**Closed** 2022-04-23 07:24 UTC
